name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - staging
        default: 'staging'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Build
    runs-on:
      group: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Unit Tests
        run: npm run test -- --run

      - name: Integration Tests
        run: npm run test:integration

      - name: Build
        run: npm run build:production
  deploy-staging:
    name: Deploy to Staging
    needs: test
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    uses: ./.github/workflows/railway-deploy.yml
    with:
      environment: staging
    secrets:
      railway_token: ${{ secrets.RAILWAY_STAGING_TOKEN }}
      staging_service_id: ${{ secrets.RAILWAY_STAGING_SERVICE_ID }}

  deploy-production:
    name: Deploy to Production
    needs: [deploy-staging]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/railway-deploy.yml
    with:
      environment: production
    secrets:
      railway_token: ${{ secrets.RAILWAY_TOKEN }}
      production_service_id: ${{ secrets.RAILWAY_PRODUCTION_SERVICE_ID }}
