name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Railway
    runs-on:
      group: self-hosted
    environment: production

    steps:
      - name: Deploy to Staging
        needs: test
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
        uses: ./.github/workflows/railway-deploy.yml
        with:
          environment: staging
        secrets:
          railway_token: ${{ secrets.RAILWAY_STAGING_TOKEN }}
          staging_service_id: ${{ secrets.RAILWAY_STAGING_SERVICE_ID }}

      - name: Deploy to Production
        needs: [test, deploy-staging]
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ./.github/workflows/railway-deploy.yml
        with:
          environment: production
        secrets:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          production_service_id: ${{ secrets.RAILWAY_PRODUCTION_SERVICE_ID }}

