# Legacy Supabase migration workflow
# This can be removed when migrating to Railway + Prisma

name: Supabase Migration

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode'
        type: boolean
        default: true

jobs:
  migrate:
    name: Run Migrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        
      - name: Run migrations
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "Dry run mode - migrations would be applied"
            supabase db push --dry-run
          else
            echo "Applying migrations"
            supabase db push
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}